### ISSUE TITLE
Arbitrary topoplot types

### ISSUE THREAD

**Issue by asinghvi17** [MakieOrg/TopoPlots.jl#47]
Would it make sense to add a `plottype` kwarg to `TopoPlot`, which would allow any `HeatmapLike` plot to be used in place of `contourf`?  I would love to use `surface` or even `contour`, for example.

**Comment by behinger** [comment]
maybe there is a good way. We already have an ugly if / else solution for "mesh" here:
https://github.com/MakieOrg/TopoPlots.jl/blob/c3a56f75a121d52e6552cc69a00d9a8eb433c944/src/core-recipe.jl#L104

So if this can be generalized, that would be great anyway.

But then I guess only replacing the surface command with a `plottype` would be much easier and more "surgical". I don't see the downside

**Comment by palday** [comment]
I don't have an objection to this, though I would do something more like `plotfnc=heatmap!` as a default attribute in the recipe. Then you just change 

https://github.com/MakieOrg/TopoPlots.jl/blob/2523bd2b827b42607d5763638501e52d59fc2cf0/src/core-recipe.jl#L120

to use `plotfnc` instead of `heatmap!`.

**Comment by palday** [comment]
closed by #56
